export const shopData = [
  {
    id: 1,
    imagePath: "/boostersm.jpg",
    category: "Special Mix",
    title: "Booster Special Mix",
    oldPrice: "121",
    newPrice: "90",
    description: "Stimulates firmness and fullness of the saggy breasts.",
  },
  {
    id: 2,
    imagePath: "/booster xl.jpg",
    category: "Special Mix",
    title: "Booster XL",
    oldPrice: "121",
    newPrice: "90",
    description:
      "Stimulates firmness, fullness and increase in the size of the breast.",
  },
  {
    id: 3,
    imagePath: "/dawo da martaba.jpg",
    category: "Aphrodisiac",
    title: "Dawo da Martaba",
    oldPrice: "121",
    newPrice: "90",
    description: "Sexual stimulant to boost ones sex drive.",
  },
  {
    id: 4,
    imagePath: "/hips and butt.jpg",
    category: "Special Mix",
    title: "Hips and Butt",
    oldPrice: "121",
    newPrice: "90",
    description: "Lorem ipsum.",
  },
  {
    id: 5,
    imagePath: "/infection kit.jpg",
    category: "Special Mix",
    title: "Infection kit",
    oldPrice: "121",
    newPrice: "90",
    description: "General body system cleanser for both male and female",
  },
  {
    id: 6,
    imagePath: "/libido booster.jpg",
    category: "Aphrodisiac",
    title: "Libido Tea",
    oldPrice: "121",
    newPrice: "90",
    description:
      "This tea boosts ones libido and increases overall sex drive in both male and female.",
  },
  {
    id: 7,
    imagePath: "/martaba10x.jpg",
    category: "Aphrodisiac",
    title: "Martaba x10",
    oldPrice: "121",
    newPrice: "90",
    description: "Sexual stimulant to boost ones sex drive.",
  },
  {
    id: 8,
    imagePath: "/penis enlargement.jpg",
    category: "Special Mix",
    title: "Penis Enlargement",
    oldPrice: "121",
    newPrice: "90",
    description:
      "This stimulates an irreversible increase in the size of the penis.",
  },
  {
    id: 9,
    imagePath: "/tightme up.jpg",
    category: "Special Mix",
    title: "Tight me up",
    oldPrice: "121",
    newPrice: "90",
    description: "Stimulates the loose walls of the vigina to tighten up.",
  },
]
