export const shopData = [
  {
    id: 1,
    imagePath: "/boostersm.png",
    category: "Special Mix",
    title: "Booster Special Mix",
    oldPrice: "4500",
    newPrice: "4000",
    description: "Stimulates firmness and fullness of the saggy breasts.",
  },
  {
    id: 2,
    imagePath: "/booster xl.png",
    category: "Special Mix",
    title: "Booster XL",
    oldPrice: "4500",
    newPrice: "4000",
    description:
      "Stimulates firmness, fullness and increase in the size of the breast.",
  },
  {
    id: 3,
    imagePath: "/dawo da martaba.png",
    category: "Aphrodisiac",
    title: "Dawo da Martaba",
    oldPrice: "4500",
    newPrice: "4000",
    description: "Sexual stimulant to boost ones sex drive.",
  },
  {
    id: 4,
    imagePath: "/hips and butt.png",
    category: "Special Mix",
    title: "Hips and Butt",
    oldPrice: "4500",
    newPrice: "4000",
    description: "Lorem ipsum.",
  },
  {
    id: 5,
    imagePath: "/infection kit.png",
    category: "Special Mix",
    title: "Infection kit",
    oldPrice: "4500",
    newPrice: "4000",
    description: "General body system cleanser for both male and female",
  },
  {
    id: 6,
    imagePath: "/libido booster.png",
    category: "Aphrodisiac",
    title: "Libido Tea",
    oldPrice: "4500",
    newPrice: "4000",
    description:
      "This tea boosts ones libido and increases overall sex drive in both male and female.",
  },
  {
    id: 7,
    imagePath: "/martaba10x.png",
    category: "Aphrodisiac",
    title: "Martaba x10",
    oldPrice: "4500",
    newPrice: "4000",
    description: "Sexual stimulant to boost ones sex drive.",
  },
  {
    id: 8,
    imagePath: "/penis enlargement.png",
    category: "Special Mix",
    title: "Penis Enlargement",
    oldPrice: "4500",
    newPrice: "4000",
    description:
      "This stimulates an irreversible increase in the size of the penis.",
  },
  {
    id: 9,
    imagePath: "/tightme up.png",
    category: "Special Mix",
    title: "Tight me up",
    oldPrice: "4500",
    newPrice: "4000",
    description: "Stimulates the loose walls of the vigina to tighten up.",
  },
]
